package com.dante.biz.apiInfo.dao;

import java.util.List;

import com.dante.model.apiInfo.ApiColumn;

public interface ApiColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String apiColumnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    int insert(ApiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    int insertSelective(ApiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    ApiColumn selectByPrimaryKey(String apiColumnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_COLUMN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiColumn record);

    /**
     * 根据apiInfoId删除参数
     * @param apiInfoId
     */
	int deleteByApiInfoId(String apiInfoId);

	List<ApiColumn> selectByApiColumn(ApiColumn apiColumn);
}