package com.dante.biz.apiInfo.dao;

import java.util.List;

import com.dante.model.apiInfo.ApiInfo;
import com.dante.model.apiInfo.ApiInfoParam;

public interface ApiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String apiInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    int insert(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    int insertSelective(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    ApiInfo selectByPrimaryKey(String apiInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_API_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiInfo record);

    /**
     * 查询接口信息列表
     *
     * @dante
     */
	List<ApiInfo> queryApiInfoList(ApiInfoParam param);
}