package com.dante.biz.apiInfo.dao;

import com.dante.model.apiInfo.ColumnInfo;

public interface ColumnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String columnInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    int insert(ColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    int insertSelective(ColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    ColumnInfo selectByPrimaryKey(String columnInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DANTE_COLUMN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ColumnInfo record);
}